// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhU30vuZBESSsbLf7mS9cltx_8HSsqUtE',
    appId: '1:643800093991:web:c4bfa6bd398795438d4502',
    messagingSenderId: '643800093991',
    projectId: 'super-vortec',
    authDomain: 'super-vortec.firebaseapp.com',
    storageBucket: 'super-vortec.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKV4D63zZsD5wuiz3QHyw-rE-58EDMRos',
    appId: '1:643800093991:android:c537050367bc18ff8d4502',
    messagingSenderId: '643800093991',
    projectId: 'super-vortec',
    storageBucket: 'super-vortec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT8Jd95xAp6RkTkXV4TO_FvpzRCu6Ybj4',
    appId: '1:643800093991:ios:76c2c4f2e9e6979d8d4502',
    messagingSenderId: '643800093991',
    projectId: 'super-vortec',
    storageBucket: 'super-vortec.firebasestorage.app',
    iosBundleId: 'com.example.superVortec',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCT8Jd95xAp6RkTkXV4TO_FvpzRCu6Ybj4',
    appId: '1:643800093991:ios:76c2c4f2e9e6979d8d4502',
    messagingSenderId: '643800093991',
    projectId: 'super-vortec',
    storageBucket: 'super-vortec.firebasestorage.app',
    iosBundleId: 'com.example.superVortec',
  );
}
